### ISSUE TITLE
cannot post on oracle cloud?! /vps-ip /arm64

### ISSUE THREAD

**Issue by beansofhell** [sekai-soft/freebird#4]
![image](https://github.com/sekai-soft/freebird/assets/126506518/72109f82-f46c-434e-9b4b-d0adf52093ce)

it wont let me login on my vps.... 

but works fine when I use docker on my local pc :( 

I will let you ssh to my vps bro if you wanna debug it

**Comment by beansofhell** [comment]
![image](https://github.com/sekai-soft/freebird/assets/126506518/8bf19006-466f-458b-9627-87134e09de19)

**Comment by beansofhell** [comment]
![image](https://github.com/sekai-soft/freebird/assets/126506518/48814955-3ce6-448a-b516-a3bbf15bb75f)


WHY ON VPS IT DOESNT WORK. DO THEY HAVE SOMETHING TO DO WITH THE RATELIMITING???

I AM USING IT AS A VPN TOO, SO WHY IT DOESNT WORK

**Comment by KTachibanaM** [comment]
It's very possible that the VPS IPs are banned from the Twitter side, especially the search APIs, so there is not much that we can do here unfortunately, though I'm planning to deploy another instance for crossposting on OCI so I'll see if I encounter similar rate limit issues
